// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using QuizApp.Data;

#nullable disable

namespace QuizApp.Data.EndToEnd
{
    public partial class EndtoendContext : IdentityDbContext
    {
        public EndtoendContext()
        {
        }

        public EndtoendContext(DbContextOptions<EndtoendContext> options)
            : base(options)
        {
        }

        public virtual DbSet<JobModel> jobModel { get; set; }
       
        public virtual DbSet<Liga> liga { get; set; }
        public virtual DbSet<Spieltag> spieltag { get; set; }
        public virtual DbSet<Verein> verein { get; set; }
        public virtual DbSet<Torjäger> torjäger { get; set; }
        public virtual DbSet<Match> match { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");
           
            //modelBuilder.Entity<JobModel>(entity =>
            //{
            //    entity.Property(e => e.Id).ValueGeneratedNever();

            //    entity.Property(e => e.Description).IsFixedLength(true);

            //    entity.Property(e => e.Status).IsFixedLength(true);
            //});

            //OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}