// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace QuizApp.Data
{
    public partial class JobModel
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(10)]
        public JobStatuses Status { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdated { get; set; }
        public string UserName { get; set; }
    }

    public enum JobStatuses
    {
        Todo,
        Started,
        Completed
    }
}